#!/usr/bin/env bash 

# remove tmp's leftover from a bad shutdown
rm -f /tmp/mongodb-27017.sock

# make the path for the database
DATABASE_PATH="$(node -e 'console.log(require("./package.json").parameters.databaseSetup.databasePath)')"
mkdir -p "$DATABASE_PATH"

# make the path for the log
LOG_FILE_PATH="$(node -e 'console.log(require("./package.json").parameters.paths.serverLog)')"
mkdir -p "$(dirname "$LOG_FILE_PATH")"

# actually start
pm2 start mongod --name "mongo" --log "$LOG_FILE_PATH" -- --repair --bind_ip 127.0.0.1 --dbpath "$DATABASE_PATH"
echo "logs sent to: $LOG_FILE_PATH"