#!/usr/bin/env bash 

# make the path for the log
LOG_FILE_PATH="$(node -e 'console.log(require("./package.json").parameters.paths.serverLog)')"
mkdir -p "$(dirname "$LOG_FILE_PATH")"

# actually start
pm2 --name "mongo" --log "$LOG_FILE_PATH" start ./settings/commands/db/raw_start.sh
echo "logs sent to: $LOG_FILE_PATH"