#!/usr/bin/env bash
function git_sync { # git push && git pull
    args="$@"
    if [[ $args = "" ]]; then
        git add -A && git commit -m "-";git pull --no-edit;git push
    else
        git add -A && git commit -m "$args";git pull --no-edit;git push
    fi
}
git_sync "$@"
ssh -t jeff@csce-jiang1.engr.tamu.edu "git pull;./settings/commands/processes/restart_all"