#!/usr/bin/env bash 

function find_process {
    application=$1
    echo "$(ps aux | grep "$application" | grep -v " grep ")"
}

echo "node:"
find_process "npx nodemon"
find_process "node main.js"
echo "mongo:"
find_process "mongod --bind_ip 127.0.0.1"
find_process "mongod --repair --bind_ip 127.0.0.1"