#!/usr/bin/env bash
kill "$(cat "$(node -e 'console.log(require("./package.json").parameters.paths.mongoPid)')")"
kill "$(cat "$(node -e 'console.log(require("./package.json").parameters.paths.expressPid)')")"