#!/usr/bin/env bash

# make the path for the log
LOG_FILE_PATH="$(node -e 'console.log(require("./package.json").parameters.paths.serverLog)')"
mkdir -p "$(dirname "$LOG_FILE_PATH")"

npx pm2 --service-name "express" --log "$LOG_FILE_PATH" start ./settings/commands/server/raw_start.sh